# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76593770e27ab7fa9507e4ac32391e30d5945437ab3e50a5f87915e5122b396d21b9ea518e85e57b537026b192c26d939f1269a84826a9acd25da53c3cce5c1a

test:
  secret_key_base: a6509446a6051dcde8f6a070fc968ea6f711c9b1470ac739d9e09561b0c45b8aec4d1c067a6b3876f71e94e67e78346a504f8a94d72b1eaf5f971a38e8b5466e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
